import type { ImageSourcePropType } from 'react-native';

/** Literal requires let Metro bundle every offline native fallback. */
export const LOCAL_FLAG_PNG_BY_REGION: Readonly<Record<string, ImageSourcePropType>> = Object.freeze({
  FR: require('./png/FR.png'),
  GB: require('./png/GB.png'),
  ES: require('./png/ES.png'),
  DE: require('./png/DE.png'),
  IT: require('./png/IT.png'),
  PT: require('./png/PT.png'),
  NL: require('./png/NL.png'),
  PL: require('./png/PL.png'),
  RU: require('./png/RU.png'),
  CN: require('./png/CN.png'),
  JP: require('./png/JP.png'),
  KR: require('./png/KR.png'),
  SA: require('./png/SA.png'),
  IN: require('./png/IN.png'),
  TR: require('./png/TR.png'),
  SE: require('./png/SE.png'),
  VN: require('./png/VN.png'),
  TH: require('./png/TH.png'),
  GR: require('./png/GR.png'),
  CZ: require('./png/CZ.png'),
  RO: require('./png/RO.png'),
  HU: require('./png/HU.png'),
  DK: require('./png/DK.png'),
  FI: require('./png/FI.png'),
  ID: require('./png/ID.png'),
  NO: require('./png/NO.png'),
  UA: require('./png/UA.png'),
  CD: require('./png/CD.png'),
  TZ: require('./png/TZ.png'),
  SN: require('./png/SN.png'),
  NG: require('./png/NG.png'),
  IL: require('./png/IL.png'),
  TW: require('./png/TW.png'),
  BD: require('./png/BD.png'),
});
