import { toSupportedLanguage } from '@second-brain/shared';

type Rule = readonly [RegExp, (...parts: string[]) => string];

/**
 * Backend copy generated by deterministic engines is still static product copy.
 * Keep it here, versioned and reviewable, instead of sending it to an LLM.
 *
 * English is the canonical persisted form. French is the currently complete
 * server-side catalogue used by the shipped FR/EN experience. Other supported
 * locales safely receive canonical copy until their reviewed catalogue lands;
 * they never trigger an AI request.
 */
const FR_EXACT: Readonly<Record<string, string>> = {
  "I couldn't find anything in your documents to answer that question.":
    "Je n’ai rien trouvé dans tes documents pour répondre à cette question.",
  'Still learning': 'Encore en apprentissage',
  Mornings: 'Le matin',
  Afternoons: "L’après-midi",
  Evenings: 'Le soir',
  'Late nights': 'Tard le soir',
  Reading: 'Lecture',
  Dialogue: 'Dialogue',
  Balanced: 'Équilibré',
  'Simple & concrete': 'Simple et concret',
  'Deep & thorough': 'Approfondi et détaillé',
  'Hands-on practice': 'Pratique active',
  'Strong spaced recall': 'Mémorisation espacée solide',
  'Steady spaced recall': 'Mémorisation espacée régulière',
  'Needs frequent review': 'Révisions fréquentes nécessaires',
  'Flashcards & spaced review': 'Cartes mémoire et révision espacée',
  'Active practice': 'Pratique active',
  'Lessons + review': 'Leçons et révision',
  'Do some spaced reviews and I’ll learn how your memory holds.':
    'Fais quelques révisions espacées et je découvrirai comment ta mémoire retient.',
  'As you study at different times, I’ll spot when you perform best.':
    'En étudiant à différents moments, je repérerai quand tu es le plus efficace.',
  'I’ll learn whether practice, reading or dialogue suits you as you use them.':
    'Je découvrirai si la pratique, la lecture ou le dialogue te convient le mieux.',
  'As you take lessons, I’ll learn how deep your explanations should go.':
    'Au fil des leçons, je saurai jusqu’où approfondir mes explications.',
  'I’ll learn which formats stick best for you as you use more of them.':
    'Je découvrirai quels formats t’aident le mieux à retenir.',
  'Clear, simple explanations land best — concrete over abstract.':
    'Les explications claires et simples fonctionnent le mieux : le concret avant l’abstrait.',
  'A balance of intuition and rigour suits you.':
    'Un équilibre entre intuition et rigueur te convient.',
  'You engage with deep, thorough explanations — detail helps rather than hinders.':
    'Tu progresses avec des explications approfondies : les détails t’aident.',
  'Practising and being tested retains better for you than re-reading.':
    'La pratique et les tests t’aident davantage à retenir que la relecture.',
  'A written lesson followed by spaced review is your most reliable format so far.':
    'Une leçon écrite suivie de révisions espacées est pour l’instant ton format le plus fiable.',
  'Yesterday’s material is coming back — clear the queue first.':
    'Le contenu d’hier revient : commence par vider la file de révision.',
  'Prerequisites are mastered — this is the right next step.':
    'Les prérequis sont maîtrisés : c’est la bonne prochaine étape.',
  'Flagged as at risk — practice beats re-reading.':
    'Signalé comme fragile : la pratique vaut mieux que la relecture.',
  'A short pass before sleep locks the day in.':
    'Une courte révision avant de dormir consolide la journée.',
  'Some vocabulary is due — a short review keeps it from fading.':
    'Du vocabulaire est à revoir : une courte révision évitera qu’il ne s’efface.',
  'Your foundations are solid — this is the right moment to build on them.':
    'Tes bases sont solides : c’est le bon moment pour progresser.',
  'You are up to date. Come back when something is due.':
    'Tu es à jour. Reviens lorsqu’une révision sera prévue.',
  'Nothing is due — add a lesson or a language to get started.':
    'Rien n’est à revoir : ajoute une leçon ou une langue pour commencer.',
  'Consolidating now prevents the gap from widening.':
    'Consolider maintenant empêche la lacune de s’aggraver.',
  'Its foundations are already mastered.': 'Ses bases sont déjà maîtrisées.',
  'Welcome back': 'Bon retour',
  'These are now above the mastery threshold — durable, long-term knowledge.':
    'Ces notions dépassent maintenant le seuil de maîtrise : un acquis durable.',
  'Each completed lesson feeds new material into your long-term memory.':
    'Chaque leçon terminée alimente ta mémoire à long terme.',
  'A steady weekly cadence — keep protecting the slot.':
    'Un rythme hebdomadaire régulier : continue à préserver ce créneau.',
  'A little light this week — a small daily slot would lift it.':
    'La semaine est un peu légère : un petit créneau quotidien aiderait.',
  'This is when your activity peaks — schedule the hard work here.':
    'C’est là que ton activité culmine : programme ici le travail difficile.',
  'The tutor adapts its explanations to this.':
    'Le professeur adapte ses explications à ce profil.',
  'The rhythm behind your progress.': 'Le rythme qui soutient tes progrès.',
  'The mean recall probability across every concept you are tracking.':
    'La probabilité moyenne de rappel pour toutes les notions suivies.',
  'From your graded exercises so far.': 'D’après tes exercices évalués jusqu’ici.',
  'It is flagged at risk — a review now stops the gap from widening.':
    'Cette notion est fragile : une révision maintenant évitera que la lacune s’aggrave.',
  'Overdue reviews are the fastest points to recover — memory is decaying on these.':
    'Les révisions en retard sont les points les plus rapides à récupérer : le souvenir s’estompe.',
  'Your weakest tracked concept — the highest-leverage place to improve.':
    'Ta notion suivie la plus fragile : le meilleur levier de progression.',
  'Shift to active recall': 'Passe au rappel actif',
  'No clear strengths yet — they appear as you master concepts.':
    'Aucune force nette pour le moment : elles apparaîtront à mesure que tu maîtriseras des notions.',
  'Nothing is slipping right now — well held.':
    'Rien ne s’affaiblit pour le moment : tes acquis tiennent bien.',
  'You are moving forward — here is the evidence.':
    'Tu progresses : voici les éléments qui le montrent.',
  'Not much progress recorded yet — complete a session to start the trail.':
    'Encore peu de progrès enregistrés : termine une session pour commencer le suivi.',
  'How you study, seen from your own data.':
    'Ta façon d’étudier, observée à partir de tes propres données.',
  'The hard numbers on how you are doing.': 'Les chiffres concrets de ta progression.',
  'No performance data yet — answer some exercises and reviews.':
    'Pas encore de données de performance : fais quelques exercices et révisions.',
  'The highest-leverage things to work on next.':
    'Les prochains travaux qui auront le plus d’impact.',
  'Nothing urgent to fix — keep the momentum.':
    'Rien d’urgent à corriger : garde ton élan.',
  'Nothing tracked yet — starting at beginner level.':
    'Aucune notion suivie : commençons au niveau débutant.',
  "You're finding this hard right now, so I'll slow the pace and consolidate.":
    'Tu rencontres des difficultés en ce moment : je vais ralentir et consolider.',
  'A steady pace fits where you are — consistent, not rushed.':
    'Un rythme régulier correspond à ton niveau : constant, sans précipitation.',
  "You're just starting — read and absorb the material first.":
    'Tu débutes : commence par lire et assimiler le contenu.',
  'You know this well — I’ll question you to deepen it rather than re-explain.':
    'Tu maîtrises bien ce sujet : je vais te questionner pour l’approfondir plutôt que tout réexpliquer.',
  'A mix of explanation and practice suits your current level.':
    'Un mélange d’explications et de pratique convient à ton niveau actuel.',
  'You set this yourself.': 'Tu as défini ce réglage.',
  'Your method is working — the effort you put in is turning into real mastery.':
    'Ta méthode fonctionne : tes efforts se transforment en véritable maîtrise.',
  'Your approach is roughly on track; keep favouring active recall over passive review.':
    'Ton approche est globalement bonne ; privilégie le rappel actif à la relecture passive.',
  "It's too early to call your trajectory — let's get some concepts tracked first.":
    'Il est trop tôt pour évaluer ta trajectoire : commençons par suivre quelques notions.',
  "You're on track for strong results — keep the momentum and stretch into harder material.":
    'Tu es sur la voie de très bons résultats : garde cet élan et aborde des contenus plus exigeants.',
  'A solid foundation is forming — consolidate the middling concepts to lift your outcomes.':
    'Une base solide se forme : consolide les notions intermédiaires pour améliorer tes résultats.',
  'Your current grasp is fragile — we should shore up the fundamentals before pushing ahead.':
    'Ta compréhension actuelle est fragile : renforçons les fondamentaux avant d’avancer.',
  'No exams on the horizon — steady, unhurried progress is the goal.':
    'Aucun examen à l’horizon : vise une progression régulière et sans précipitation.',
  'No upcoming exams scheduled.': 'Aucun examen à venir.',
  'You show up consistently — that regularity is doing a lot of the work for you.':
    'Tu étudies avec régularité : cette constance joue beaucoup en ta faveur.',
  "You're forming a rhythm — protect a fixed daily slot so it becomes automatic.":
    'Tu construis un rythme : préserve un créneau quotidien fixe pour en faire une habitude.',
  'Your study rhythm is irregular — one small, fixed daily session beats occasional long ones.':
    'Ton rythme est irrégulier : une petite session quotidienne vaut mieux que de longues sessions occasionnelles.',
  "You're succeeding more than you're struggling — trust that, and take on a harder challenge.":
    'Tu réussis plus souvent que tu ne rencontres de difficultés : fais-toi confiance et relève un défi plus exigeant.',
  'Your confidence should track your progress — small, visible wins are the fastest way to grow it.':
    'Ta confiance doit suivre tes progrès : de petites réussites visibles la feront grandir rapidement.',
  "You're in a good place across the board — let's keep the momentum and aim higher.":
    'Ta situation est bonne sur tous les plans : gardons cet élan et visons plus haut.',
  'Your review load is light right now.': 'Ta charge de révision est légère actuellement.',
  "I'll trim today's plan and spread the reviews over several days.":
    'Je vais alléger le programme du jour et répartir les révisions sur plusieurs jours.',
  'No change needed — the load is manageable.':
    'Aucun changement nécessaire : la charge est gérable.',
  "You're engaged and showing up regularly.": 'Tu es impliqué et tu étudies régulièrement.',
  'Automatically lighten the plan and offer one short, easy win to return to.':
    'Alléger automatiquement le programme et proposer une courte réussite facile pour reprendre.',
  'Nudge with a short, low-effort session to rebuild the habit.':
    'Proposer une session courte et accessible pour reconstruire l’habitude.',
  'Keep the current rhythm — nothing to change.': 'Garde le rythme actuel : rien à changer.',
  'The road ahead looks clear.': 'La suite du parcours paraît dégagée.',
  'Consolidate the shaky concepts before opening new ground.':
    'Consolide les notions fragiles avant d’en ouvrir de nouvelles.',
  'Continue — no roadblocks ahead.': 'Continue : aucun obstacle en vue.',
  'Very little activity this week.': 'Très peu d’activité cette semaine.',
  "You're staying engaged.": 'Tu restes impliqué.',
  'Celebrate a recent win and set one tiny, achievable goal to restart momentum.':
    'Célèbre une réussite récente et fixe un tout petit objectif atteignable pour relancer l’élan.',
  'Momentum is fine — keep going.': 'Ton élan est bon : continue.',
  'Nothing is about to be forgotten.': 'Rien ne risque d’être oublié prochainement.',
  'Review these ahead of time, before recall drops.':
    'Révise ces éléments à l’avance, avant que le rappel ne diminue.',
  'Your memory is holding — no early review needed.':
    'Ta mémoire tient bon : aucune révision anticipée n’est nécessaire.',
  'Review what is due': 'Réviser les éléments dus',
  'Review now': 'Réviser maintenant',
  'Prepare now': 'Se préparer maintenant',
  'Upcoming exam': 'Examen à venir',
  'Urgent review': 'Révision urgente',
  'Review due': 'Révision due',
  'Resume your learning session': 'Reprendre ta session d’apprentissage',
  Resume: 'Reprendre',
  'This session has a saved place to continue from.':
    'Cette session possède un point de reprise enregistré.',
  'Continue without losing context': 'Continuer sans perdre le contexte',
  'Interrupted session': 'Session interrompue',
  'Active session': 'Session active',
  'The session has a verified resume destination and preserved context.':
    'La session possède une destination de reprise vérifiée et un contexte préservé.',
  'Coach recommendation': 'Recommandation du coach',
  'Mentor suggestion': 'Suggestion du mentor',
  'Foresight estimate': 'Estimation prédictive',
  'Adapt my plan': 'Adapter mon plan',
  Continue: 'Continuer',
  Start: 'Commencer',
  'View goal': 'Voir l’objectif',
  'Move your goal forward': 'Faire avancer ton objectif',
  'Active goal': 'Objectif actif',
  'Start learning': 'Commencer à apprendre',
  'Second Brain is still getting to know you.':
    'Second Brain apprend encore à te connaître.',
  'Getting started': 'Premiers pas',
  'No learning activity, review, exam, session or goal is available yet.':
    'Aucune activité d’apprentissage, révision, examen, session ou objectif n’est encore disponible.',
  'Explore a new subject': 'Explorer un nouveau sujet',
  Explore: 'Explorer',
  'Nothing urgent is due right now.': 'Rien d’urgent n’est dû pour le moment.',
  'Up to date': 'À jour',
  'No due review, close exam or resumable priority was found.':
    'Aucune révision due, aucun examen proche ni aucune priorité à reprendre n’a été trouvé.',
};

const FR_RULES: readonly Rule[] = [
  [/^Prepare for (.+)$/, (subject) => `Préparer ${subject}`],
  [/^Your exam is today\.$/, () => 'Ton examen a lieu aujourd’hui.'],
  [/^Your exam is in (\d+) days?\.$/, (n) => `Ton examen a lieu dans ${n} jour${n === '1' ? '' : 's'}.`],
  [/^(.+): (\d+) days? remaining\.(?: Preparation is (\d+)%\.)?$/, (subject, n, preparation) => `${subject} : ${n} jour${n === '1' ? '' : 's'} restant${n === '1' ? '' : 's'}.${preparation ? ` Préparation : ${preparation} %.` : ''}`],
  [/^(\d+) reviews? (?:is|are) due now\.$/, (n) => `${n} révision${n === '1' ? ' est due' : 's sont dues'} maintenant.`],
  [/^Continue (.+)$/, (title) => `Continuer ${title}`],
  [/^Review (.+)$/, (title) => `Réviser ${title}`],
  [/^Practice (.+)$/, (title) => `Pratiquer ${title}`],
  [/^This is your current (daily|weekly|monthly) goal\.$/, (period) => `Il s’agit de ton objectif ${period === 'daily' ? 'quotidien' : period === 'weekly' ? 'hebdomadaire' : 'mensuel'} actuel.`],
  [/^The goal “(.+)” is still in progress\.$/, (title) => `L’objectif « ${title} » est toujours en cours.`],
  [/^(\d+) flashcards?$/, (n) => `${n} carte${n === '1' ? '' : 's'} mémoire`],
  [/^At your current pace, the (dropout|difficulty|overload|motivation|forgetting) risk is estimated at (\d+)%\. (.+)$/, (kind, probability, cause) => `À ton rythme actuel, le risque ${kind === 'dropout' ? 'd’abandon' : kind === 'difficulty' ? 'de difficulté' : kind === 'overload' ? 'de surcharge' : kind === 'motivation' ? 'de démotivation' : 'd’oubli'} est estimé à ${probability} %. ${cause}`],
  [/^Estimated probability: (\d+)%\. (.+)$/, (probability, evidence) => `Probabilité estimée : ${probability} %. ${evidence}`],
  [/^You retain (\d+)% of what you review — spaced repetition works very well for you\.$/, (p) => `Tu retiens ${p} % de ce que tu révises : la répétition espacée fonctionne très bien pour toi.`],
  [/^You retain (\d+)% across reviews — spacing helps, with the occasional refresher\.$/, (p) => `Tu retiens ${p} % au fil des révisions : l’espacement aide, avec quelques rappels ponctuels.`],
  [/^You retain (\d+)% so far — shorter, more frequent reviews will suit your memory better\.$/, (p) => `Tu retiens ${p} % pour l’instant : des révisions plus courtes et fréquentes conviendront mieux à ta mémoire.`],
  [/^Your activity peaks in the (.+) — that’s when to schedule the hard work\.$/, (period) => `Ton activité culmine ${period} : programme le travail difficile à ce moment-là.`],
  [/^Your dominant modality: (.+)\.$/, (mode) => `Ta modalité dominante : ${mode}.`],
  [/^Spaced flashcards give you the best retention \((\d+)%\) — lean on them\.$/, (p) => `Les cartes mémoire espacées t’offrent la meilleure rétention (${p} %) : appuie-toi sur elles.`],
  [/^Review (\d+) due cards?$/, (n) => `Réviser ${n} carte${n === '1' ? '' : 's'} prévue${n === '1' ? '' : 's'}`],
  [/^New lesson: (.+)$/, (name) => `Nouvelle leçon : ${name}`],
  [/^Your grasp here is (.+); today builds it up\.$/, (level) => `Ta maîtrise est actuellement ${level} ; la séance du jour va la renforcer.`],
  [/^Exercises: (.+)$/, (name) => `Exercices : ${name}`],
  [/^(.+): (\d+) words? to review$/, (language, n) => `${language} : ${n} mot${n === '1' ? '' : 's'} à revoir`],
  [/^Keep (.+) vocabulary from slipping\.$/, (language) => `Empêche ton vocabulaire en ${language} de s’effacer.`],
  [/^Quick revision — (\d+) cards?$/, (n) => `Révision rapide — ${n} carte${n === '1' ? '' : 's'}`],
  [/^(\d+) (.+) words? to review$/, (n, language) => `${n} mot${n === '1' ? '' : 's'} en ${language} à revoir`],
  [/^you are gradually forgetting (.+)$/, (name) => `tu oublies progressivement ${name}`],
  [/^ready to move forward on (.+)$/, (name) => `prêt à progresser sur ${name}`],
  [/^Today I suggest (.+)\.$/, (plan) => `Aujourd’hui, je te propose ${plan}.`],
  [/^You are gradually forgetting (.+)\. Reviewing now catches it just before it slips\.$/, (name) => `Tu oublies progressivement ${name}. Le revoir maintenant permet d’agir juste avant qu’il ne s’efface.`],
  [/^Practice: (.+)$/, (name) => `Pratiquer : ${name}`],
  [/^You're gradually forgetting "(.+)" — targeted exercises will pull it back\.$/, (name) => `Tu oublies progressivement « ${name} » : des exercices ciblés vont le consolider.`],
  [/^Review (\d+) items?$/, (n) => `Réviser ${n} élément${n === '1' ? '' : 's'}`],
  [/^(\d+) items? (?:is|are) due — a short review locks them in\.$/, (n) => `${n} élément${n === '1' ? ' est prévu' : 's sont prévus'} : une courte révision les consolidera.`],
  [/^You've mastered what "(.+)" builds on — you're ready to start it\.$/, (name) => `Tu maîtrises les prérequis de « ${name} » : tu peux commencer.`],
  [/^Read: (.+)$/, (title) => `Lire : ${title}`],
  [/^This supports "(.+)", which is on your path right now\.$/, (name) => `Ce contenu renforce « ${name} », qui se trouve actuellement sur ton parcours.`],
  [/^Try a practical on (.+)$/, (name) => `Faire une mise en pratique sur ${name}`],
  [/^You've mastered "(.+)" — applying it in practice makes it permanent\.$/, (name) => `Tu maîtrises « ${name} » : la mise en pratique rendra cet acquis durable.`],
  [/^Connect: (.+)$/, (title) => `Relier : ${title}`],
  [/^"(.+)" isn't linked to any concept yet — extracting it grows your Digital Twin\.$/, (title) => `« ${title} » n’est encore relié à aucune notion : son analyse enrichira ton jumeau numérique.`],
  [/^Let's slow down on (.+)$/, (name) => `Ralentissons sur ${name}`],
  [/^(.+), "(.+)" has been tough lately\. I'll slow the pace and we'll revisit the basics before moving on\.$/, (user, name) => `${user}, « ${name} » est difficile en ce moment. Je vais ralentir et nous reprendrons les bases avant d’avancer.`],
  [/^"(.+)" is flagged at risk(?: \(mastery (\d+)%\))?\.$/, (name, p) => `« ${name} » est signalé comme fragile${p ? ` (maîtrise ${p} %)` : ''}.`],
  [/^(\d+) reviews are due$/, (n) => `${n} révisions sont prévues`],
  [/^(.+), you have (\d+) items due for review\. A short session now will lock them into long-term memory\.$/, (user, n) => `${user}, tu as ${n} éléments à revoir. Une courte session maintenant les ancrera dans ta mémoire à long terme.`],
  [/^(\d+) FSRS cards are at or past their review date\.$/, (n) => `${n} cartes FSRS ont atteint ou dépassé leur date de révision.`],
  [/^Ready to start (.+)$/, (name) => `Prêt à commencer ${name}`],
  [/^(.+), you've mastered what "(.+)" builds on — I think you're ready to start it\.$/, (user, name) => `${user}, tu maîtrises les prérequis de « ${name} » : tu peux commencer.`],
  [/^"(.+)" has no unmet prerequisites\.$/, (name) => `« ${name} » n’a aucun prérequis non acquis.`],
  [/^Good to see you again, (.+)\. Let's ease back in with a short, gentle session\.$/, (name) => `Ravi de te revoir, ${name}. Reprenons en douceur avec une courte session.`],
  [/^No activity for (\d+) days\.$/, (n) => `Aucune activité depuis ${n} jours.`],
  [/^You have (\d+) solid strengths?\.$/, (n) => `Tu as ${n} force${n === '1' ? '' : 's'} solide${n === '1' ? '' : 's'}.`],
  [/^(\d+) concepts? need attention\.$/, (n) => `${n} notion${n === '1' ? '' : 's'} nécessite${n === '1' ? '' : 'nt'} ton attention.`],
  [/^Mastered at (\d+)% \((\d+)★\) — a reliable strength you can build on\.$/, (p, stars) => `Maîtrisé à ${p} % (${stars}★) : une force fiable sur laquelle t’appuyer.`],
  [/^Only (\d+)% mastered — this is slipping and needs consolidation\.$/, (p) => `Seulement ${p} % de maîtrise : cette notion s’affaiblit et doit être consolidée.`],
  [/^(\d+) concepts? mastered$/, (n) => `${n} notion${n === '1' ? '' : 's'} maîtrisée${n === '1' ? '' : 's'}`],
  [/^Learning Score rose across (\d+) sessions?$/, (n) => `Le score d’apprentissage a progressé sur ${n} session${n === '1' ? '' : 's'}`],
  [/^Those sessions added about (\d+) points of Learning Score in total\.$/, (n) => `Ces sessions ont ajouté environ ${n} points au score d’apprentissage.`],
  [/^(\d+) lessons? completed$/, (n) => `${n} leçon${n === '1' ? '' : 's'} terminée${n === '1' ? '' : 's'}`],
  [/^(\d+)-day streak$/, (n) => `Série de ${n} jour${n === '1' ? '' : 's'}`],
  [/^Your longest run is (\d+) days? — consistency is what compounds\.$/, (n) => `Ta plus longue série est de ${n} jour${n === '1' ? '' : 's'} : la régularité fait la différence.`],
  [/^(\d+) sessions? this week$/, (n) => `${n} session${n === '1' ? '' : 's'} cette semaine`],
  [/^You focus best (.+)$/, (hours) => `Tu te concentres le mieux entre ${hours}`],
  [/^Your learning leans (.+)$/, (style) => `Ton apprentissage privilégie ${style}`],
  [/^(\d+) study interactions logged$/, (n) => `${n} interactions d’apprentissage enregistrées`],
  [/^Average mastery (\d+)%$/, (p) => `Maîtrise moyenne : ${p} %`],
  [/^Exercise accuracy (\d+)%$/, (p) => `Précision aux exercices : ${p} %`],
  [/^Across your last (\d+) graded answers?\.$/, (n) => `Sur tes ${n} dernière${n === '1' ? '' : 's'} réponse${n === '1' ? '' : 's'} évaluée${n === '1' ? '' : 's'}.`],
  [/^Memory retention (\d+)%$/, (p) => `Rétention mémorielle : ${p} %`],
  [/^The share of your (\d+) reviews? you recalled successfully\.$/, (n) => `La part des ${n} révision${n === '1' ? '' : 's'} rappelée${n === '1' ? '' : 's'} avec succès.`],
  [/^Revisit "(.+)"$/, (name) => `Revoir « ${name} »`],
  [/^Clear (\d+) due reviews$/, (n) => `Effectuer ${n} révisions prévues`],
  [/^Strengthen "(.+)"$/, (name) => `Renforcer « ${name} »`],
  [/^Your accuracy \((\d+)%\) suggests re-reading isn't sticking — testing yourself will\.$/, (p) => `Ta précision (${p} %) montre que la relecture ne suffit pas : te tester sera plus efficace.`],
  [/^Your average mastery is (\d+)% — you can handle advanced material\.$/, (p) => `Ta maîtrise moyenne est de ${p} % : tu peux aborder un contenu avancé.`],
  [/^Your average mastery is (\d+)% — intermediate is the right stretch\.$/, (p) => `Ta maîtrise moyenne est de ${p} % : le niveau intermédiaire est le bon défi.`],
  [/^Your average mastery is (\d+)% — let's rebuild the basics first\.$/, (p) => `Ta maîtrise moyenne est de ${p} % : reconstruisons d’abord les bases.`],
  [/^A (\d+)-day streak and solid mastery — you can take on more\.$/, (n) => `Une série de ${n} jours et une maîtrise solide : tu peux aller plus loin.`],
  [/^Your exercises are landing at (\d+)% — more practice will fix that\.$/, (p) => `Tes exercices atteignent ${p} % : davantage de pratique améliorera cela.`],
  [/^Your sessions typically run about (\d+) min — I’ll plan around that\.$/, (n) => `Tes sessions durent généralement environ ${n} min : je m’adapterai à ce rythme.`],
  [/^Starting at (\d+) min until I learn your rhythm\.$/, (n) => `Commençons par ${n} min, le temps que j’apprenne ton rythme.`],
  [/^Preparation (\d+)% from mastery of "(.+)"\.$/, (p, subject) => `Préparation à ${p} % d’après la maîtrise de « ${subject} ».`],
  [/^No concept is linked to "(.+)" yet, so preparation can't be measured\.$/, (subject) => `Aucune notion n’est encore reliée à « ${subject} » ; la préparation ne peut pas être mesurée.`],
  [/^"(.+)" is linked but has no reviewed cards yet — preparation can't be measured\.$/, (subject) => `« ${subject} » est relié, mais aucune carte n’a encore été révisée ; la préparation ne peut pas être mesurée.`],
  [/^(\d+) reviewed cards? of (\d+) — the evidence base for this estimate\.$/, (reviewed, total) => `${reviewed} carte${reviewed === '1' ? '' : 's'} révisée${reviewed === '1' ? '' : 's'} sur ${total} : la base de cette estimation.`],
  [/^(\d+) days? until the exam\.$/, (n) => `${n} jour${n === '1' ? '' : 's'} avant l’examen.`],
  [/^Model confidence (\d+)% \((.+)\)\.$/, (p, band) => `Confiance du modèle : ${p} % (${band}).`],
  [/^Study a few cards on "(.+)" — once they're reviewed I can measure and track your readiness\.$/, (subject) => `Étudie quelques cartes sur « ${subject} » ; une fois révisées, je pourrai suivre ta préparation.`],
  [/^Link "(.+)" to its concepts \(and study a few cards\) so I can measure your readiness\.$/, (subject) => `Relie « ${subject} » à ses notions et étudie quelques cartes afin que je puisse mesurer ta préparation.`],
  [/^Do a few review sessions on "(.+)" — more reviews will both raise and sharpen this estimate\.$/, (subject) => `Fais quelques sessions de révision sur « ${subject} » : elles augmenteront et préciseront cette estimation.`],
  [/^You're in great shape — keep "(.+)" warm with light spaced reviews until the exam\.$/, (subject) => `Ta préparation est excellente : entretiens « ${subject} » avec de légères révisions espacées jusqu’à l’examen.`],
  [/^Time is short — focus your remaining sessions on the weakest parts of "(.+)"\.$/, (subject) => `Le temps presse : concentre tes dernières sessions sur les points les plus fragiles de « ${subject} ».`],
  [/^Steady daily review of "(.+)" will lift your readiness well before the exam\.$/, (subject) => `Une révision quotidienne régulière de « ${subject} » renforcera ta préparation bien avant l’examen.`],
];

export function translateStaticCopy(text: string, locale: string): string {
  if (!text?.trim()) return text;
  const code = toSupportedLanguage(locale);
  if (!code || code === 'en') return text;
  if (code !== 'fr') return text;

  const exact = FR_EXACT[text];
  if (exact) return exact;
  for (const [pattern, replace] of FR_RULES) {
    const match = pattern.exec(text);
    if (match) return replace(...match.slice(1));
  }
  return text;
}
