import type { Locale } from './i18n';

const copy = {
  en: {
    usersTitle: 'Users', usersSubtitle: 'Server-paginated directory. Only authorized administrative data is shown.',
    user: 'User', email: 'Email', userId: 'User ID', accountStatus: 'Account status', plan: 'Plan', subscription: 'Subscription', quotaState: 'Quota state', usagePercent: 'Usage', country: 'Country', interfaceLanguage: 'Interface language', createdAt: 'Created at', lastActive: 'Last active', yes: 'Yes', no: 'No',
    searchUsers: 'Search by user ID, email or name', search: 'Search', clearFilters: 'Clear filters', filters: 'Filters', sorting: 'Sorting', sortNewest: 'Newest first', sortOldest: 'Oldest first', sortLastActive: 'Last active', sortEmail: 'Email',
    all: 'All', active: 'Active', suspended: 'Suspended', banned: 'Banned', deletionPending: 'Deletion pending', free: 'FREE', pro: 'PRO', proMax: 'PRO MAX', primary: 'Primary', fallback: 'Fallback', blocked: 'Blocked', pastDue: 'Past due', paymentFailed: 'Payment failed', canceled: 'Canceled', expired: 'Expired',
    directorySummary: 'Directory summary', results: 'results', page: 'Page', previous: 'Previous', next: 'Next', noUsers: 'No users match the current search and filters.', loadUsersError: 'Unable to load users.', retry: 'Retry', loading: 'Loading…', forbidden: 'You do not have permission to view this information.',
    userControlCenter: 'User administration control center', backToUsers: 'Back to users', refresh: 'Refresh', refreshed: 'User data refreshed.', available: 'Available', notAvailable: 'Not available', noData: 'No data available', notInstrumented: 'NOT INSTRUMENTED', unavailableEnvironment: 'This data is not available in this environment.',
    overview: 'Overview', account: 'Account', learnerProfile: 'Learner profile', subscriptionPanel: 'Subscription', quotas: 'Quotas', usage: 'Usage', payments: 'Payments', security: 'Security', activity: 'Activity', supportAudit: 'Support / audit', dangerZone: 'Danger zone',
    emailVerified: 'Email verified', identityVerification: 'Identity verification', identityNotImplemented: 'NOT IMPLEMENTED', profileClassification: 'Profile data classification', standard: 'Standard', restricted: 'Restricted', highlyRestricted: 'Highly restricted', sensitiveReason: 'Reason for sensitive access', requestSensitiveAccess: 'Request sensitive access', sensitiveAccessHint: 'Highly restricted learner data is hidden by default. A reason is required and the server records the audit event.',
    educationLevel: 'Education level', curriculum: 'Curriculum / track', subjects: 'Subjects', learningGoals: 'Learning goals', nativeLanguage: 'Native language', studyLanguage: 'Study language', mobilityContext: 'International mobility context', learningPreferences: 'Learning preferences', teacherPreferences: 'Teacher preferences', cefr: 'CEFR', learningDna: 'Learning DNA summary', profileReview: 'Profile review',
    billingInterval: 'Billing interval', currentPeriodStart: 'Current period start', currentPeriodEnd: 'Current period end', nextRenewal: 'Next renewal', provider: 'Provider', providerReference: 'Provider reference', cancelAtPeriodEnd: 'Cancel at period end', planHistory: 'Plan history', adminOverride: 'ADMIN OVERRIDE',
    resource: 'Resource', state: 'State', primaryUsed: 'Primary used', primaryLimit: 'Primary limit', fallbackUsed: 'Fallback used', fallbackLimit: 'Fallback limit', percentage: 'Percentage', resetAt: 'Reset at', overallUsage: 'Overall usage', adjustQuota: 'Adjust quota', adjustmentResource: 'Resource code', adjustmentAmount: 'Amount', adjustmentCycleId: 'Active cycle ID (optional)',
    engine: 'Engine', metric: 'Metric', value: 'Value', languageText: 'Language text', languageVoice: 'Language voice', documentsMetadata: 'Document metadata only',
    lastPayment: 'Last payment', amount: 'Amount', currency: 'Currency', paymentStatus: 'Status', paymentDate: 'Date', paymentFailures: 'Payment failures', refunds: 'Refunds', paymentHistory: 'Payment history', referenceMasked: 'Reference (masked)', invoice: 'Invoice',
    activeSessions: 'Active sessions', sessionCreated: 'Created', lastUsed: 'Last used', device: 'Device', ipMetadata: 'IP metadata', sessionStatus: 'Status', revokeAllSessions: 'Revoke all sessions',
    suspensionHistory: 'Suspension history', banHistory: 'Ban history', securityEvents: 'Security events', auditHistory: 'Admin action history', who: 'Who', action: 'Action', when: 'When', reason: 'Reason', result: 'Result', supportNotes: 'Support notes', supportNote: 'Internal note', noteBody: 'Note', noteReason: 'Why this note is necessary', addSupportNote: 'Add internal note', notesSafetyHint: 'Internal, audited support context only. Do not enter passwords, OTPs, tokens, payment credentials or other secrets.', reportsIncidents: 'Reports and incidents', userErrors: 'User-specific errors', internalNotesUnavailable: 'Support notes are not instrumented in this release.',
    suspendUser: 'Suspend user', reactivateUser: 'Reactivate user', banUser: 'Ban user', requestDeletion: 'Request account deletion', deletionRequestedAt: 'Requested at', deletionRequestedBy: 'Requested by', deletionReason: 'Reason', deletionStatus: 'Status',
    planOverride: 'Plan override', grantBetaAccess: 'Grant beta access', betaProTest: 'PRO TEST', betaProMaxTest: 'PRO MAX TEST', startsAt: 'Starts at', expiresAt: 'Expires at', selectPlan: 'Select plan',
    actionRequiresMfa: 'A reason and a recent MFA step-up are required. This action is audited.', typeConfirm: 'Type CONFIRM', cancel: 'Cancel', confirm: 'Confirm', working: 'Working…', actionFailed: 'The action could not be completed.', stepUpRequired: 'MFA step-up required', stepUpHint: 'Enter the current authenticator code to continue this audited action.', authenticationCode: 'Authentication code', verifyAndContinue: 'Verify and continue',
    suspendConsequence: 'Suspending denies login and revokes every current session.', reactivateConsequence: 'Reactivation permits a new login; revoked sessions stay revoked.', banConsequence: 'Banning denies access. It does not delete user data.', deletionConsequence: 'This creates a privacy workflow request. It does not delete data now.', revokeConsequence: 'All current sessions will be revoked. Tokens are never displayed.',
    noBulkActions: 'Bulk account and quota mutations are intentionally unavailable.', detailsUnavailable: 'Unable to load this user.', statusActive: 'ACTIVE', statusSuspended: 'SUSPENDED', statusBanned: 'BANNED', statusDeletionPending: 'DELETION_PENDING',
  },
  fr: {
    usersTitle: 'Utilisateurs', usersSubtitle: 'Annuaire paginé côté serveur. Seules les données administratives autorisées sont affichées.',
    user: 'Utilisateur', email: 'E-mail', userId: 'ID utilisateur', accountStatus: 'État du compte', plan: 'Plan', subscription: 'Abonnement', quotaState: 'État des quotas', usagePercent: 'Usage', country: 'Pays', interfaceLanguage: 'Langue d’interface', createdAt: 'Créé le', lastActive: 'Dernière activité', yes: 'Oui', no: 'Non',
    searchUsers: 'Rechercher par ID, e-mail ou nom', search: 'Rechercher', clearFilters: 'Réinitialiser les filtres', filters: 'Filtres', sorting: 'Tri', sortNewest: 'Plus récents', sortOldest: 'Plus anciens', sortLastActive: 'Dernière activité', sortEmail: 'E-mail',
    all: 'Tous', active: 'Actif', suspended: 'Suspendu', banned: 'Banni', deletionPending: 'Suppression en attente', free: 'FREE', pro: 'PRO', proMax: 'PRO MAX', primary: 'Principal', fallback: 'Repli', blocked: 'Bloqué', pastDue: 'Impayé', paymentFailed: 'Paiement échoué', canceled: 'Annulé', expired: 'Expiré',
    directorySummary: 'Synthèse de l’annuaire', results: 'résultats', page: 'Page', previous: 'Précédent', next: 'Suivant', noUsers: 'Aucun utilisateur ne correspond à la recherche et aux filtres.', loadUsersError: 'Impossible de charger les utilisateurs.', retry: 'Réessayer', loading: 'Chargement…', forbidden: 'Votre rôle ne permet pas de consulter cette information.',
    userControlCenter: 'Centre d’administration utilisateur', backToUsers: 'Retour aux utilisateurs', refresh: 'Actualiser', refreshed: 'Données utilisateur actualisées.', available: 'Disponible', notAvailable: 'Non disponible', noData: 'Aucune donnée disponible', notInstrumented: 'NON INSTRUMENTÉ', unavailableEnvironment: 'Ces données ne sont pas disponibles dans cet environnement.',
    overview: 'Vue d’ensemble', account: 'Compte', learnerProfile: 'Profil apprenant', subscriptionPanel: 'Abonnement', quotas: 'Quotas', usage: 'Usage', payments: 'Paiements', security: 'Sécurité', activity: 'Activité', supportAudit: 'Support / audit', dangerZone: 'Zone dangereuse',
    emailVerified: 'E-mail vérifié', identityVerification: 'Vérification d’identité', identityNotImplemented: 'NON IMPLÉMENTÉ', profileClassification: 'Classification des données de profil', standard: 'Standard', restricted: 'Restreint', highlyRestricted: 'Très restreint', sensitiveReason: 'Motif de l’accès sensible', requestSensitiveAccess: 'Demander l’accès sensible', sensitiveAccessHint: 'Les données apprenant très restreintes sont masquées par défaut. Un motif est obligatoire et le serveur journalise l’accès.',
    educationLevel: 'Niveau d’études', curriculum: 'Programme / parcours', subjects: 'Matières', learningGoals: 'Objectifs pédagogiques', nativeLanguage: 'Langue maternelle', studyLanguage: 'Langue d’étude', mobilityContext: 'Contexte de mobilité internationale', learningPreferences: 'Préférences d’apprentissage', teacherPreferences: 'Préférences enseignant', cefr: 'CECR', learningDna: 'Synthèse Learning DNA', profileReview: 'Revue de profil',
    billingInterval: 'Périodicité', currentPeriodStart: 'Début de période', currentPeriodEnd: 'Fin de période', nextRenewal: 'Prochain renouvellement', provider: 'Fournisseur', providerReference: 'Référence fournisseur', cancelAtPeriodEnd: 'Annulation en fin de période', planHistory: 'Historique des plans', adminOverride: 'ADMIN OVERRIDE',
    resource: 'Ressource', state: 'État', primaryUsed: 'Principal utilisé', primaryLimit: 'Limite principale', fallbackUsed: 'Repli utilisé', fallbackLimit: 'Limite de repli', percentage: 'Pourcentage', resetAt: 'Réinitialisation', overallUsage: 'Usage global', adjustQuota: 'Ajuster le quota', adjustmentResource: 'Code ressource', adjustmentAmount: 'Montant', adjustmentCycleId: 'ID de cycle actif (facultatif)',
    engine: 'Moteur', metric: 'Métrique', value: 'Valeur', languageText: 'Langues texte', languageVoice: 'Langues voix', documentsMetadata: 'Métadonnées de documents uniquement',
    lastPayment: 'Dernier paiement', amount: 'Montant', currency: 'Devise', paymentStatus: 'État', paymentDate: 'Date', paymentFailures: 'Échecs de paiement', refunds: 'Remboursements', paymentHistory: 'Historique des paiements', referenceMasked: 'Référence masquée', invoice: 'Facture',
    activeSessions: 'Sessions actives', sessionCreated: 'Créée', lastUsed: 'Dernière utilisation', device: 'Appareil', ipMetadata: 'Métadonnées IP', sessionStatus: 'État', revokeAllSessions: 'Révoquer toutes les sessions',
    suspensionHistory: 'Historique des suspensions', banHistory: 'Historique des bannissements', securityEvents: 'Événements de sécurité', auditHistory: 'Historique des actions Admin', who: 'Par', action: 'Action', when: 'Quand', reason: 'Motif', result: 'Résultat', supportNotes: 'Notes support', supportNote: 'Note interne', noteBody: 'Note', noteReason: 'Pourquoi cette note est nécessaire', addSupportNote: 'Ajouter une note interne', notesSafetyHint: 'Contexte support interne et audité uniquement. Ne saisissez ni mot de passe, OTP, jeton, information de paiement ni autre secret.', reportsIncidents: 'Signalements et incidents', userErrors: 'Erreurs propres à l’utilisateur', internalNotesUnavailable: 'Les notes support ne sont pas instrumentées dans cette version.',
    suspendUser: 'Suspendre l’utilisateur', reactivateUser: 'Réactiver', banUser: 'Bannir l’utilisateur', requestDeletion: 'Demander la suppression du compte', deletionRequestedAt: 'Demandée le', deletionRequestedBy: 'Demandée par', deletionReason: 'Motif', deletionStatus: 'État',
    planOverride: 'Dérogation de plan', grantBetaAccess: 'Accorder un accès bêta', betaProTest: 'PRO TEST', betaProMaxTest: 'PRO MAX TEST', startsAt: 'Début', expiresAt: 'Expiration', selectPlan: 'Choisir le plan',
    actionRequiresMfa: 'Un motif et une élévation MFA récente sont obligatoires. Cette action est auditée.', typeConfirm: 'Saisir CONFIRM', cancel: 'Annuler', confirm: 'Confirmer', working: 'Traitement…', actionFailed: 'L’action n’a pas pu être effectuée.', stepUpRequired: 'Élévation MFA requise', stepUpHint: 'Saisissez le code actuel de votre application d’authentification pour poursuivre cette action auditée.', authenticationCode: 'Code d’authentification', verifyAndContinue: 'Vérifier et poursuivre',
    suspendConsequence: 'La suspension refuse la connexion et révoque toutes les sessions en cours.', reactivateConsequence: 'La réactivation autorise une nouvelle connexion ; les sessions révoquées le restent.', banConsequence: 'Le bannissement refuse l’accès. Il ne supprime pas les données utilisateur.', deletionConsequence: 'Cette action crée une demande du workflow Privacy. Elle ne supprime pas les données immédiatement.', revokeConsequence: 'Toutes les sessions en cours seront révoquées. Les jetons ne sont jamais affichés.',
    noBulkActions: 'Les mutations de comptes et quotas en masse sont volontairement indisponibles.', detailsUnavailable: 'Impossible de charger cet utilisateur.', statusActive: 'ACTIF', statusSuspended: 'SUSPENDU', statusBanned: 'BANNI', statusDeletionPending: 'SUPPRESSION_EN_ATTENTE',
  },
} as const;

export type UserCopyKey = keyof typeof copy.en;

export function u(locale: Locale, key: UserCopyKey): string {
  return copy[locale][key];
}

export function userStatusLabel(locale: Locale, value: unknown): string {
  const normalized = String(value ?? '').trim().toUpperCase().replace(/[ -]/g, '_');
  const labels: Record<string, UserCopyKey> = {
    ACTIVE: 'active', SUSPENDED: 'suspended', BANNED: 'banned', DELETION_PENDING: 'deletionPending',
    FREE: 'free', PRO: 'pro', PRO_MAX: 'proMax', PRIMARY: 'primary', FALLBACK: 'fallback', BLOCKED: 'blocked',
    PAST_DUE: 'pastDue', PAYMENT_FAILED: 'paymentFailed', CANCELED: 'canceled', EXPIRED: 'expired', NOT_INSTRUMENTED: 'notInstrumented', NOT_IMPLEMENTED: 'identityNotImplemented',
  };
  return labels[normalized] ? u(locale, labels[normalized]) : (typeof value === 'string' && value ? value : u(locale, 'notAvailable'));
}
