import { Injectable } from '@nestjs/common';
import type { LearningMemory, MemoryEntry } from '@second-brain/shared';
import { PrismaService } from '../prisma/prisma.service';

const TIMELINE_LIMIT = 60;

const RATING_LABEL: Record<number, string> = {
  1: 'Again',
  2: 'Hard',
  3: 'Good',
  4: 'Easy',
};

/**
 * Learning Memory Engine (task 4.2) — the pedagogical memory.
 *
 * The app already persists everything the learner does; this composes those
 * records into one unified, chronological memory (with a summary of how much is
 * remembered), so the AI — and the learner — can see that nothing starts from
 * zero. Read-only: it never writes, it remembers what is already there.
 */
@Injectable()
export class MemoryService {
  constructor(private readonly prisma: PrismaService) {}

  async timeline(userId: string): Promise<LearningMemory> {
    const [lessons, attempts, reviews, sessions, homework, reports, documents] =
      await Promise.all([
        this.prisma.lesson.findMany({
          where: { userId },
          select: { id: true, topic: true, createdAt: true, sourceDocumentId: true },
        }),
        this.prisma.exerciseAttempt.findMany({
          where: { userId },
          select: { id: true, question: true, correct: true, createdAt: true },
        }),
        this.prisma.reviewLog.findMany({
          where: { userId },
          select: {
            id: true,
            rating: true,
            reviewedAt: true,
            card: { select: { front: true } },
          },
        }),
        this.prisma.tutorSession.findMany({
          where: { userId },
          select: {
            id: true,
            title: true,
            subject: true,
            updatedAt: true,
            _count: { select: { messages: true } },
          },
        }),
        this.prisma.homework.findMany({
          where: { userId },
          select: { id: true, focus: true, createdAt: true, lesson: { select: { topic: true } } },
        }),
        this.prisma.studySession.findMany({
          where: { userId, status: 'done' },
          select: { id: true, subject: true, completedAt: true },
        }),
        this.prisma.document.findMany({
          where: { userId },
          select: { id: true, title: true, source: true, createdAt: true },
        }),
      ]);

    // Documents generated by the lesson engine are already remembered as
    // lessons — only surface the ones the learner actually brought in.
    const lessonDocIds = new Set(
      lessons.map((l) => l.sourceDocumentId).filter((id): id is string => !!id),
    );
    const studied = documents.filter((d) => !lessonDocIds.has(d.id));

    const entries: MemoryEntry[] = [];
    for (const l of lessons) {
      entries.push({
        id: `lesson-${l.id}`,
        kind: 'lesson',
        title: l.topic,
        detail: 'Lesson studied',
        subject: l.topic,
        at: l.createdAt.toISOString(),
      });
    }
    for (const a of attempts) {
      entries.push({
        id: `attempt-${a.id}`,
        kind: a.correct ? 'success' : 'error',
        title: a.question,
        detail: a.correct ? 'Answered correctly' : 'Mistake — corrected by the Examiner',
        subject: null,
        at: a.createdAt.toISOString(),
      });
    }
    for (const r of reviews) {
      entries.push({
        id: `review-${r.id}`,
        kind: 'revision',
        title: r.card?.front ?? 'Flashcard',
        detail: `Reviewed · ${RATING_LABEL[r.rating] ?? 'rated'}`,
        subject: null,
        at: r.reviewedAt.toISOString(),
      });
    }
    for (const s of sessions) {
      entries.push({
        id: `tutor-${s.id}`,
        kind: 'conversation',
        title: s.title ?? s.subject ?? 'Discussion',
        detail: `${s._count.messages} messages`,
        subject: s.subject,
        at: s.updatedAt.toISOString(),
      });
    }
    for (const h of homework) {
      entries.push({
        id: `homework-${h.id}`,
        kind: 'homework',
        title: h.lesson?.topic ?? 'Homework',
        detail: h.focus.slice(0, 140),
        subject: h.lesson?.topic ?? null,
        at: h.createdAt.toISOString(),
      });
    }
    for (const r of reports) {
      if (!r.completedAt) continue;
      entries.push({
        id: `report-${r.id}`,
        kind: 'report',
        title: r.subject,
        detail: 'Study session completed',
        subject: r.subject,
        at: r.completedAt.toISOString(),
      });
    }
    for (const d of studied) {
      entries.push({
        id: `doc-${d.id}`,
        kind: 'document',
        title: d.title,
        detail: `Document studied (${d.source})`,
        subject: null,
        at: d.createdAt.toISOString(),
      });
    }

    entries.sort((a, b) => b.at.localeCompare(a.at));

    const errors = attempts.filter((a) => !a.correct).length;
    const successes = attempts.length - errors;

    return {
      summary: {
        lessons: lessons.length,
        exercises: attempts.length,
        errors,
        successes,
        revisions: reviews.length,
        conversations: sessions.length,
        homework: homework.length,
        reports: reports.filter((r) => r.completedAt).length,
        documents: studied.length,
        total: entries.length,
      },
      entries: entries.slice(0, TIMELINE_LIMIT),
    };
  }
}
